site_name: "Hanjo Winter – Web · UX · Storytelling"
subtitle: "Profil & Portfolio – Web · UX · Storytelling"
base_url: "http://localhost:8000"
theme: "soft-teal"
language: "de"
show_posts: false
show_timeline: true
show_projects: true

cache:
  enabled: false

navigation:
  - slug: "home"
    label: "Start"
  - slug: "about"
    label: "Über mich"
  - slug: "projects"
    label: "Projekte"
  - slug: "timeline"
    label: "Werdegang"
